services:
  - type: web
    name: resume-parser-api
    env: python
    region: oregon
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y libreoffice poppler-utils tesseract-ocr
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
